name: Build Win32 D3D App
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2
    - name: Compile
      shell: cmd
      run: cl /EHsc /O2 /Fe:MyApp.exe main.cpp /link user32.lib d3d11.lib dxgi.lib d2d1.lib dwrite.lib
    - uses: actions/upload-artifact@v4
      with:
        name: myapp-exe
        path: MyApp.exe
